# Generated by Django 4.0.4 on 2022-06-25 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp', models.ImageField(default='default.jpg', upload_to='MoriKeliDps/')),
                ('bio', models.TextField(max_length=500)),
                ('estate', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=14)),
                ('facebook_link', models.URLField()),
                ('instagram_link', models.URLField()),
                ('twitter_link', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=30)),
                ('university_desc', models.TextField()),
                ('university_degree', models.CharField(max_length=50)),
                ('high_school', models.CharField(max_length=30)),
                ('highsch_desc', models.TextField()),
                ('resume_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Portofolio',
            fields=[
                ('project_id', models.UUIDField(default=uuid.UUID('a7fd8403-485b-4d39-aaa4-c61469d2f065'), editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Art', 'Art'), ('Python Program', 'Python Program'), ('Web development', 'Web development')], max_length=100)),
                ('project_thumbnail', models.ImageField(upload_to='Portofolio Thumbnails/')),
                ('github_link', models.URLField()),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.profile')),
            ],
            options={
                'verbose_name_plural': 'Portofolio',
            },
        ),
    ]
