# Generated by Django 4.0.4 on 2022-06-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dp',
            field=models.ImageField(default='default.jng', upload_to='MoriKeliDps/'),
        ),
    ]
